name: biliNFT scraper
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
jobs:
  scrapeNFT:
    runs-on: ubuntu-latest
    name: Scrape biliNFT
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: scrape biliNFT
        run: |
          pip install natsorted
          python scraper.py
          python emotescraper.py ${{secrets.EMOTEURL}}

      - name: commit
        run: |
          git config --global user.email 106490582+lovegaoshi@users.noreply.github.com
          git config --global user.name lovegaoshi
          git add .
          git commit -m "chore: weekly scrape" -a

      - name: Push changes to master
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
